on:
  push:
    branches: main

name: 🚀 Deploy dev-site on push on the dev branch
jobs:
  web-deploy:
    name: 🎉 Deploy1
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3        
        
      - name: 📂 Sync FrontEnd files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          # exclude: |
          #  **/.vscode/**
          #  **/.git*
          #  **/.git*/**
          #  **/node_modules/**
          #  *lock.json
          server-dir: ./dev2.wunderber.com/
          # dangerous-clean-slate: true
